# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'CareemMovies' do

  pod 'Gloss', '~> 1.2'
  pod 'Kingfisher', '~> 3.0'

  target 'CareemMoviesTests' do
    inherit! :search_paths
 
  end

end
