# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'CareemMovies' do

  pod 'Gloss', '~> 1.2'
  pod 'Kingfisher', '~> 3.0'
  pod 'RealmSwift'
  
  target 'CareemMoviesTests' do
    inherit! :search_paths
    
    pod 'RealmSwift'
 
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
